start launches minikube with 16gb #WS-2

diff --git a/infra/scripts/environment/start-cluster b/infra/scripts/environment/start-cluster
--- a/infra/scripts/environment/start-cluster
+++ b/infra/scripts/environment/start-cluster
@@ -9,3 +9,22 @@ else
     MINIKUBE_VERSION=$(minikube version | grep -Po "minikube version: \K[^ ]+")
     echo "Minikube is installed! ${MINIKUBE_VERSION}"
 fi
+
+echo "Checking Minikube status..."
+MINIKUBE_STATUS=$(minikube status)
+if [ $? -ne 0 ]; then
+    echo "Minikube not running, starting..."
+    minikube start --memory=16384 || { echo "Minikube failed to start..."; exit 1; }
+
+    MINIKUBE_STATUS=$(minikube status)
+    if [ $? -ne 0 ]; then
+        echo "Minikube failed to start..."
+        echo $MINIKUBE_STATUS
+        exit 1
+    fi
+else
+    echo "Minikube is running..."
+fi
+
+MINIKUBE_IP=$(minikube ip)
+echo "Minikube is running on ${MINIKUBE_IP}"
